/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // 1. ARES OS 2.0 Sidebar
  // Since 'intro.md' is likely at the root, we define this manually or 
  // you can move ARES core docs into a 'docs/ares' folder for cleaner separation.
  aresSidebar: [
    {
      type: 'autogenerated',
      dirName: 'ares',
    },
  ],

  // 2. PyAres Sidebar
  // Automatically generates a sidebar from the 'docs/pyares' folder
  pyaresSidebar: [
    {
      type: 'autogenerated',
      dirName: 'pyares',
    },
  ],

  // 3. ARES Launcher Sidebar
  launcherSidebar: [
    {
      type: 'autogenerated',
      dirName: 'launcher',
    },
  ],

  // 4. Datamodel Sidebar
  datamodelSidebar: [
    {
      type: 'autogenerated',
      dirName: 'datamodel',
    },
  ],

  // 5. ATHENA Sidebar
  athenaSidebar: [
    {
      type: 'autogenerated',
      dirName: 'athena',
    },
  ],
};

module.exports = sidebars;